#!/usr/bin/env bash

echo "doing the grid layout plots"
for inlist in grid*.inlist; do
     echo "   running $inlist..."
     ./run_test $inlist
done

echo "doing the example plots"
for inlist in plt*.inlist; do
    echo "   running $inlist..."
    ./run_test $inlist
done
